version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: Docker/nginx.Dockerfile
    ports:
      - 1994:80
    links:
        - fpm
    volumes:
        - ./:/var/www/

  fpm:
    build:
      context: .
      dockerfile: Docker/fpm.Dockerfile
    volumes:
      - ./:/var/www/
    links: 
      - mysql

  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=quizqondb79
      - MYSQL_ROOT_PASSWORD=Asdf+963
      - MYSQL_USER=admin2
      - MYSQL_PASSWORD=Asdf+963+2

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Asdf+963